= doco2podans, Docker Compose to Podman Ansible converter

The idea would be to transform Docker Compose yaml files into Ansible playbooks using the https://github.com/containers/ansible-podman-collections[containers.podman collection] to reach the same effect.

NOTE: at this stage it is just an idea, not sure I'll find ever the time and the need to work properly on this.
You're better off trying your luck with https://github.com/containers/podman-compose[podman-compose] for now.

I've already converted (manually) some https://github.com/docker-library/docs/blob/master/nextcloud/README.md#running-this-image-with-docker-compose[Nextcloud docker-compose example] to https://gitlab.com/EricPublic/miscericlaneous/-/tree/master/nextcloud_atomic[Docker Ansible], then to https://gitlab.com/EricPublic/miscericlaneous/-/tree/master/nextcloud_container[Podman Ansible].
I didn't find it too difficult (after the podman collection was released) despite some quirks, especially around networking.

The advantage is more programmatical flexibility given by Ansible, and the possibility to intermingle the automation with non-container aspects.

== Usage

.Usage
----
./dc2pa.py [--depends-network] [--kind <playbook|tasks>] \
	[--state <present|absent>] [--secret-exists <skip_existing|force>]
	<docker-compose.yml> [podman-ansible.yml]
----

At this stage, doco2podans only outputs either a playbook or a tasks file (if you want to create a role out of it), either to stdout or to a file given.

You'll then only have to call the playbook with sudo-rights to deploy the environment:

----
ansible-playbook -K podman-ansible.yml
----

The `--depends-network` option is interesting to make sure that the containers can resolve each other's name via DNS if they depend on each other.
It is created jointly with the "linked" networks and is the alternative to adding the `dnsname` to the default podman network.

You can use the `--state` option to create two different playbook, one to deploy the environment (the default), one to destroy it:

----
./dc2pa.py docker-compose.yml playbook-up.yml
./dc2pa.py --state absent docker-compose.yml playbook-down.yml
ansible-playbook -K playbook-up.yml
# use the environment...
ansible-playbook -K playbook-down.yml
----

CAUTION: make sure to use the same `--depends-network` option with both calls of `dc2pa.py` or you might get an inconsistent result.

And the `--secret-exists` option allows to decide if existing secrets should be skipped (the default) or forcefully replaced, as Ansible can't decide itself if secrets have changed or not (the content is secret!).

== Scope

The following 'docker-compose' features and options are currently mapped:

* secrets
** file
** name (key/implicit)
* volumes
** name (key/implicit)
* networks
** name (key/implicit)
* services (containers)
** build or image
** command
** depends_on
** environment
** hostname
** links
** name (key/implicit)
** ports
** restart
** secrets
** shm_size
** volumes
** volumes_from

The focus will be on freely available docker compose examples for open source products.
Feature requests will need to be supported by a link to such an example.
Requests along the line that the specs have an obscure feature unsupported by the tool, without concrete real life repeatable example, will be closed.

Also the purpose isn't to _improve_ the resulting Ansible code but to make it running as good, or as bad, as it used to run with docker-compose.
For example, secret files and environment variables are generally best replaced by Ansible vaults and variables, but this is something users will have to improve themselves, starting from a working Ansible playbook generated from the docker-compose file.

Everybody is encouraged to use the non-root feature of podman, but it is also beyond the scope of this tool to make sure that it works, as it might even imply changes to the underlying container image.
This is the reason why the playbook is created with `become: true`, but changing it into `become: false` and checking if it works isn't so big a deal.
Fixing possible incompatibilities is a bigger deal which can't be covered by doco2podans.

TIP: one of the main things to consider is to not use host ports below 1024.

== License

GPLv3+, see link:LICENSE[LICENSE].
