# from https://docs.gitlab.com/ee/install/docker.html#install-gitlab-using-docker-compose
# rm -fr ./gitlab/{data,logs,config}.myown.d
# mkdir -p ./gitlab/{data,logs,config}.myown.d
# export GITLAB_HOME=./gitlab
version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'localhost.localdomain'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost.localdomain:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - '$GITLAB_HOME/config.myown.d:/etc/gitlab'
      - '$GITLAB_HOME/logs.myown.d:/var/log/gitlab'
      - '$GITLAB_HOME/data.myown.d:/var/opt/gitlab'
    shm_size: '256m'
